version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: pgdb
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    networks:
      - backend
  webserver:
    image: puckel/docker-airflow:1.10.1
    container_name: af
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.3.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=<your fernet key here>
      - ALEKSA=BBB
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./script:/usr/local/airflow/entrypoint
      - ./requirements:/usr/local/airflow/requirements
      - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      - backend
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  backend:
    driver: "bridge"
